# Generated by Django 4.1 on 2022-09-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangKatalog',
        ),
    ]
